MVCPilotProjectWeb/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVCPilotProject.DataAccess.Repository.IRepository;
using MVCPilotProject.Models;
using MVCPilotProject.Utility;

namespace MVCPilotProjectWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.RoleAdmin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var companies = _unitOfWork.Company.GetAll();

            return View(companies);
        }

        public IActionResult Upsert(int? id)
        {

            if (id == null || id == 0)
            {
                return View(new Company());
            }
            else
            {
                Company company = _unitOfWork.Company.Get(x => x.Id == id);
                return View(company);
            }

        }

        [HttpPost]
        public IActionResult Upsert(Company newCompany)
        {
            if(ModelState.IsValid)
            {
                if(newCompany.Id == 0)
                {
                    _unitOfWork.Company.Add(newCompany);

                    TempData["success"] = "Company was successfully created!";
                }
                else
                {
                    _unitOfWork.Company.Update(newCompany);

                    TempData["success"] = "Company was successfully updated!";
                }

                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            else
            {
                return View(newCompany);
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Company? CompanyFromDb = _unitOfWork.Company.Get(x => x.Id == id);

            if (CompanyFromDb == null)
            {
                return NotFound();
            }

            _unitOfWork.Company.Remove(CompanyFromDb);
            _unitOfWork.Save();

            TempData["success"] = "Company was successfully deleted!";

            return RedirectToAction("Index");
        }

        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var companys = _unitOfWork.Company.GetAll();

            return Json(new {data = companys});
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            Company? CompanyFromDb = _unitOfWork.Company.Get(x => x.Id == id);

            if (CompanyFromDb == null)
            {
                return Json(new { success = true, data = "Error while deleting!" });
            }

            _unitOfWork.Company.Remove(CompanyFromDb);
            _unitOfWork.Save();

            return Json(new { success = true, data = "Company was successfully deleted!" });

        }

        #endregion 
    }
}

MVCPilotProjectWeb/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow borde-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    Company list
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6"></div>
            <div class="col-6 text-end">
                <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>
                    Create new company
                </a>
            </div>
        </div>

        <table id="tblData" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Address
                </th>
                <th>
                    City
                </th>
                <th>
                    State
                </th>
                <th>
                    Phone number
                </th>
                <th>
                    
                </th>
            </tr>
            </thead>
        </table>

    </div>
</div>

@section Scripts
{
    <script src="~/js/company.js"></script>
}

MVCPilotProjectWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow borde-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    @(Model.Id != 0 ? "Update" :"Create") Company
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-10">
                    <div class="border p-3">
                        @* <div asp-validation-summary="All"></div> *@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="py-2 col-12">
                            <label asp-for="StreetAddress" class="ms-2 text-muted"></label>
                            <textarea asp-for="StreetAddress" class="form-floating border-0 shadow"></textarea>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" class="form-control border-0 shadow" />
                            <label asp-for="City" class="ms-2"></label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" class="form-control border-0 shadow" />
                            <label asp-for="State" class="ms-2"></label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PhoneNumber" class="form-control border-0 shadow" />
                            <label asp-for="PhoneNumber" class="ms-2"></label>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create"</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Company" asp-action="Index" class="btn btn-outline-primary border form-control">Back to list</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          
        </form>
    </div>
</div>



@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
        <script>
            tinymce.init({
              selector: 'textarea',
              plugins: [
                'anchor', 'charmap', 'codesample', 'emoticons', 'lists', 'wordcount',
                // Your account includes a free trial of TinyMCE premium features
                // Try the most popular premium features until Jun 16, 2025:
                'checklist', 'mediaembed', 'casechange', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'permanentpen', 'powerpaste', 'advtable', 'advcode', 'editimage', 'advtemplate', 'ai', 'mentions', 'tinycomments', 'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'markdown','importword', 'exportword', 'exportpdf'
              ],
              toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent',
              tinycomments_mode: 'embedded',
              tinycomments_author: 'Author name',
              mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
              ],
              ai_request: (request, respondWith) => respondWith.string(() => Promise.reject('See docs to implement AI Assistant')),
            });
        </script>
    }
}